### ISSUE TITLE
Relative Import

### ISSUE THREAD

**Issue by michel-rodrigues** [jasonshark/angular-drf-todolist#1]
views.py --> from serializers import TodoSerializer

missing a dot before serializer :)

**Comment by connor11528** [comment]
I think it still works tho. u getting an error?

**Comment by michel-rodrigues** [comment]
Yes. 

ImportError at /
No module named 'serializers'
Exception Location: [...]/angular-drf-todolist-master/jsframework/views.py in <module>, line 5

**Comment by connor11528** [comment]
If you sub over a PR I will approve it for sure! I haven't touched Django in over a year tbh

**Comment by chdorb** [comment]
`from jsframework.serializers import TodoSerializer`
